<a href="https://colab.research.google.com/github/chaitali9977/Machine-learning-case-studies/blob/main/DAIBETES_CASE_STUDY_USING_KNN%2CPCA%2CBOOSTING_TECHNIQUES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv('/content/diabetes.csv')

In [ ]:
data.head()

In [8]:
X=data.drop(['Outcome'],axis=1)
y=data['Outcome']

In [9]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [30]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [10]:
X.shape

(768, 8)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [12]:
X_train.shape

(614, 8)

In [13]:
X_test.shape

(154, 8)

KNN

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=14)

In [15]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=14)

In [16]:
predictions=knn.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [18]:
print(cm)

[[97  7]
 [27 23]]


In [19]:
print(ac)

0.7792207792207793


PCA

In [20]:
from sklearn.decomposition import PCA

In [21]:
pca=PCA(n_components=8)
X_reduced_train=pd.DataFrame(pca.fit_transform(X_train))
X_reduced_test=pd.DataFrame(pca.fit_transform(X_test))

In [22]:
X_reduced_train.shape

(614, 8)

In [23]:
X_reduced_test.shape

(154, 8)

In [24]:
pca.n_components

8

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=14)

In [26]:
knn.fit(X_reduced_train,y_train)

KNeighborsClassifier(n_neighbors=14)

In [27]:
predictions=knn.predict(X_reduced_test)

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [29]:
print(cm)

[[87 17]
 [43  7]]


In [30]:
print(ac)

0.6103896103896104


the score is very less than KNN

LETS START WITH ANOTHER ALGORITHM

Implementing classification using Decision tree classifier

In [33]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [34]:
tree_classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [35]:
y_pred=tree_classifier.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix,top_k_accuracy_score
cm=confusion_matrix(y_pred,y_test)
ac=accuracy_score(y_pred,y_test)

In [37]:
print(cm)

[[78 19]
 [26 31]]


In [38]:
print(ac)

0.7077922077922078


Boosting the accuracy by using Adaboost

In [45]:
from sklearn.ensemble import AdaBoostClassifier
ada_classifier=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=15)

In [46]:
ada_classifier.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=15)

In [47]:
ada_predictions=ada_classifier.predict(X_test)

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(ada_predictions,y_test)
ac=accuracy_score(ada_predictions,y_test)

In [55]:
print(ac)

0.7727272727272727


Boosting the accuracy by using Gradient Boost

In [56]:
from sklearn.ensemble import GradientBoostingClassifier
gradient_classifier=GradientBoostingClassifier(learning_rate=0.01)

In [57]:
gradient_classifier.fit(X_train,y_train)

GradientBoostingClassifier(learning_rate=0.01)

In [58]:
gradient_prediction=gradient_classifier.predict(X_test)

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(gradient_prediction,y_test)
ac=accuracy_score(gradient_prediction,y_test)

In [61]:
print(ac)

0.7597402597402597
