<a href="https://colab.research.google.com/github/chaitali9977/Machine-learning-case-studies/blob/main/PCA_Dimentionality_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('/content/heart.csv')

In [23]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [24]:
X=data.drop(['target'],axis=1)
y=data['target']

In [25]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  
0   2     3  
1   0     3  
2   0     3  
3   1     3  
4   3     2

In [9]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [26]:
X.shape # independent features

(1025, 13)

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [38]:
X_train.shape

(768, 13)

In [39]:
X_test.shape

(257, 13)

KNN


In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=15)

In [29]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [30]:
predictions=knn.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [32]:
print(cm)

[[86 43]
 [31 97]]


In [33]:
print(ac)

0.7120622568093385


PCA

In [34]:
from sklearn.decomposition import PCA

In [35]:
pca=PCA(n_components=7) #n_components=principal_components
X_reduced_train=pd.DataFrame(pca.fit_transform(X_train))
X_reduced_test=pd.DataFrame(pca.fit_transform(X_test))

In [36]:
X_reduced_train.shape

(768, 7)

In [40]:
X_reduced_test.shape

(257, 7)

In [41]:
pca.n_components

7

In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=15)


In [44]:
knn.fit(X_reduced_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [45]:
predictions=knn.predict(X_reduced_test)

In [46]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [47]:
print(cm)

[[78 51]
 [32 96]]


In [48]:
print(ac)

0.6770428015564203


IF WE CHANGE THE PREDICTION DATA THEN RESULT WILL BE..

In [49]:
pca=PCA(n_components=9) #n_components=principal_components
X_reduced_train=pd.DataFrame(pca.fit_transform(X_train))
X_reduced_test=pd.DataFrame(pca.fit_transform(X_test))

In [50]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=15)

In [51]:
knn.fit(X_reduced_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [52]:
predictions=knn.predict(X_reduced_test)

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [54]:
print(cm)

[[78 51]
 [32 96]]


In [55]:
print(ac)

0.6770428015564203


In [56]:
ca=PCA(n_components=5) #n_components=principal_components
X_reduced_train=pd.DataFrame(pca.fit_transform(X_train))
X_reduced_test=pd.DataFrame(pca.fit_transform(X_test))

In [57]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=15)

In [58]:
knn.fit(X_reduced_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [59]:
predictions=knn.predict(X_reduced_test)

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [61]:
print(cm)

[[78 51]
 [32 96]]


In [62]:
print(ac)

0.6770428015564203


RESULT IS SAME THAT MEANS WE ARE ACTUALLY IN A SATURATION POINT
SO THE POINT IS KNN GIVES US 71.20 ACCURACY WHERE AS PCA GIVES US 67.70 ACCURACY. SO WE WILL GO WITH KNN CLASSIFIER 